### ISSUE TITLE
Could not load file or assembly 'SpeechClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by nvgopika** [Microsoft/ProjectOxford-ClientSDK#34]
I am getting error while selecting any option to start recognition for speech to test project.(https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/Speech/SpeechToText)
Error :An unhandled exception of type 'System.BadImageFormatException' occurred in PresentationCore.dll

Additional information: Could not load file or assembly 'SpeechClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

I have Azure account and provide primary,secondary subscriptions keys properly. Using x64.

**Comment by jasonvomsft** [comment]
This occurs when the wrong platform architecture is being used.  Be sure your application's processor matches the SpeechClient.dll architecture.

**Comment by lightfrenzy** [comment]
@nvgopika, I'm closing this out due to Jason's comment but if this doesn't resolve your issue, please reopen. Thanks!

**Comment by ajitagarwal89** [comment]
![error](https://cloud.githubusercontent.com/assets/24733403/23752107/041fbac6-04fa-11e7-9dcb-108dc9c857d5.JPG)
![error](https://cloud.githubusercontent.com/assets/24733403/23752117/0ffdfefc-04fa-11e7-9237-6751fa6fb583.JPG)
How to resolve this problem.

**Comment by ThajunNajaah** [comment]
hi,, I'm also having that same problem? Did you got that solution?

**Comment by shreyasmurthy24** [comment]
Select the project, Alt + Enter --> Build --> Platform Target --> Change to either 32 bit or 64 bit from the combo box.

**Comment by abhishek83** [comment]
Hi,
I tried above solution of changing of 32 or 64 bit, but it doesnot give any impact. I am getting below error .
I don't expect such error from MS paid service sample solution.

System.IO.FileLoadException
  HResult=0x8007007F
  Message=A procedure imported by 'SpeechClient.dll' could not be loaded.
  Source=SpeechToText-WPF-Sample
  StackTrace:
   at Microsoft.CognitiveServices.SpeechRecognition.MainWindow.RadioButton_Click(Object sender, RoutedEventArgs e) in C:\Users\efijkmr\Desktop\Cognitive-Speech-STT-Windows-master\Cognitive-Speech-STT-Windows-master\samples\SpeechRecognitionServiceExample\MainWindow.xaml.cs:line 871
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at IntellServiceExample.App.Main()

**Comment by shreyasmurthy24** [comment]
Hi,

Apologies for delayed response, I see the dll SpeechClient.dll is not
imported correctly, could you import the dll from nuget manager, build and
try running it?
The API used is from Microsoft but I was just writing the code to explore
the Cognitive Services.

Regards
Shreyas

**Comment by seahorsevn** [comment]
Hi,
I got the same issue as @abhishek83. I imported the dll from nuget manager. But it can't help.

Here is my issues with a warning and runtime error:
https://github.com/Azure-Samples/Cognitive-Speech-STT-Windows/issues/54

If this library is not official from Microsoft, could you give me some guide lines to make a similar thing? Thank you.

**Comment by shreyasmurthy24** [comment]
Hi,

I'll try to setup the  project in a completely new system, and let you
know. Thanks!!

Regards
Shreyas

**Comment by ahmad811** [comment]
I am facing same issue when running from .NET FW Console project.
However, when running from WPF app, it works

**Comment by soso-maitha** [comment]
I have same issue. I changed Target platform to 64 bit but still getting same error.

**Comment by shreyasmurthy24** [comment]
Friends, I'll rework on this, as I see many of the folks are facing the
issue with the code and configuration.

Apologies!!

Regards
Shreyas

**Comment by soso-maitha** [comment]
Thanks for your reply. Is it possible by any chance to get it fixed by tomorrow? i have to present it to my team tomorrow and to our VP after tomorrow and if i didn't make it I will be in trouble :(

**Comment by shreyasmurthy24** [comment]
Sure I'll try my level best to fix the error, honestly.

**Comment by shreyasmurthy24** [comment]
Refer this link: https://github.com/Azure-Samples/Cognitive-Speech-STT-Windows
