### ISSUE TITLE
Emotion Analysis Example

### ISSUE THREAD

**Issue by Alaakhazar** [Microsoft/ProjectOxford-ClientSDK#65]
i am trying to run this example, it works just fine for the url image, but the second one (reading an image from disk memory)  give me this error 
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 569, in run
    self.update_remote_view()
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 450, in update_remote_view
    remote_view = make_remote_view(ns, settings, more_excluded_names)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 79, in make_remote_view
    minmax=settings['minmax'])
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 225, in value_to_display
    return display
UnboundLocalError: local variable 'display' referenced before assignment

**Comment by cristiancanton** [comment]
Hello,
It seems you have some problem with the display of elements into the Spyder lib in Anaconda. May you share some more details and the code that triggered this error?

**Comment by Alaakhazar** [comment]
Hi, i was trying to run the code as it was posted in this: https://github.com/Microsoft/ProjectOxford-ClientSDK/blob/master/Emotion/Python/Jupyter%20Notebook/Emotion%20Analysis%20Example.ipynb
the part for the url image worked fine, the second part gave me the error

**Comment by Alaakhazar** [comment]
it shows the result window, the application crashes and then when i try to restore it i get the error above.

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Emotion-Python#2
