### ISSUE TITLE
Exception in emotion detection

### ISSUE THREAD

**Issue by basimolimajeed** [Microsoft/ProjectOxford-ClientSDK#87]
Hi, tried to run the sample for emotion detection on windows 10. The image is loaded then I get this exception:
[16:02:47.891793]: EmotionServiceClient is created
[16:02:47.910295]: Calling EmotionServiceClient.RecognizeAsync()...
[16:02:54.305999]: Microsoft.ProjectOxford.Common.ClientException: Exception of type 'Microsoft.ProjectOxford.Common.ClientException' was thrown.
   at Microsoft.ProjectOxford.Common.ServiceClient.<SendAsync>d__22`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Common.ServiceClient.<PostAsync>d__20`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Emotion.EmotionServiceClient.<RecognizeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Emotion.EmotionServiceClient.<RecognizeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EmotionAPI_WPF_Samples.DetectEmotionUsingStreamPage.<UploadAndDetectEmotions>d__1.MoveNext() in C:\Users\basim\Source\Repos\ProjectOxford-ClientSDK\Emotion\Windows\Sample-WPF\DetectEmotionUsingStreamPage.xaml.cs:line 113

[16:02:54.336011]: Detection Result:
[16:02:54.346018]: No emotion is detected. This might be due to:
    image is too small to detect faces
    no faces are in the images
    faces poses make it difficult to detect emotions
    or other factors

Any idea why?
Thanks

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Emotion-Windows#2
